"""add ai_insights metadata field

Revision ID: 8c1e7be34673
Revises: 
Create Date: 2025-10-28 13:52:16.027114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1e7be34673'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_income', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_expense', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('income_change_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expense_change_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_column('expense_change_pct')
        batch_op.drop_column('income_change_pct')
        batch_op.drop_column('total_expense')
        batch_op.drop_column('total_income')
        batch_op.drop_column('period')

    # ### end Alembic commands ###
